In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("NYC_Jobs.csv")

data.head()
# data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252.0,84252.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,External,NaN,82884.0,116391.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC HOUSING AUTHORITY,External,Legal Affairs,105000.0,125000.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,External,Information Technology & Telecommunications,87203.0,131623.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,External,Constituent Services & Community Programs,58449.0,67216.0

### Replacing/Fillig  NaN values with something else

### fillna() function

In [3]:
# # Just to make temporary fill to dataframe
data.fillna('Legal Affairs')


# # To make permanent fill/changes to original dataframe
# data.fillna('Legal Affairs', inplace=True)

# # OR Alternative way to make permanent fill/change to original dataframe:
# data = data.fillna('Legal Affairs')

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252.0,84252.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,External,Legal Affairs,82884.0,116391.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC HOUSING AUTHORITY,External,Legal Affairs,105000.0,125000.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,External,Information Technology & Telecommunications,87203.0,131623.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,External,Constituent Services & Community Programs,58449.0,67216.0
...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,External,Legal Affairs,62397.0,71757.0

In [4]:
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252.0,84252.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,External,NaN,82884.0,116391.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC HOUSING AUTHORITY,External,Legal Affairs,105000.0,125000.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,External,Information Technology & Telecommunications,87203.0,131623.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,External,Constituent Services & Community Programs,58449.0,67216.0
...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,External,Legal Affairs,62397.0,71757.0

### replace() function to replace value by something else value

In [5]:
# NOTE: replace() method le exact match vako value lai matra replace/change garcha

# data.replace("NYC HOUSING AUTHORITY","NYC AUTHORITY FOR HOUSING")

# #  NOTE: To make permanent replacement to the original dataframe
# # use inplace=True attribute
data.replace("NYC HOUSING AUTHORITY",'NYC_Hous_A', inplace=True)

### loc[ ]  OR   at[ ]  function to change value based on certain condition

In [7]:
# Changes the value in the original dataframe

# NOTE: data["Posting Type"]=="External" chai condition ho
# NOTE: Posting Type = 1 chai, 1 value le update/replace gareko ho
data.loc[data["Posting Type"] == "External", "Posting Type"] = 1

data.at[data["Posting Type"] == 1,'Civil Service Title']='CITA'
data.loc[0, "Posting Type"] = "Unknown" #works with at too

InvalidIndexError: You can only assign a scalar value not a <class 'str'>

In [8]:
data.loc[0, "Posting Type"] = 12

In [9]:
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,12,Health,84252.0,84252.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,1,NaN,82884.0,116391.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC_Hous_A,1,Legal Affairs,105000.0,125000.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,1,Information Technology & Telecommunications,87203.0,131623.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0
...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0

In [ ]:
data["is_LegalAffairs"] = np.where(data["Job Category"] == "Legal Affairs", 1, 0)

In [ ]:
data

In [ ]:
data['Civil Service Title'].mask(data['Civil Service Title'] == 'SENIOR IT ARCHITECT', 0, inplace=False)

In [ ]:
data

In [ ]:
def capitalize(text):
    return text.lower().capitalize()

data['Civil Service Title'].apply(capitalize)

In [ ]:
def replace_values(text):
    if text == 'NYC EMPLOYEES RETIREMENT SYS':
        return 'Retirement SYS'
    elif text == 'HUMAN RIGHTS COMMISSION':
        return 'HRC'
    else:
        return text

data['Agency'] = data['Agency'].apply(replace_values)

In [ ]:
data

In [ ]:
data['Agency'].map({'NYC HOUSING AUTHORITY':'NYC_H_A'})

In [ ]:
def add_year(value):
    return str(value) + '_2022'
    

data[['Job ID', 'Civil Service Title']] = data[['Job ID', 'Civil Service Title']].applymap(add_year)

In [ ]:
data

In [ ]:
data['Salary range'] = pd.cut(data['Salary Range From'], 3)
data

In [ ]:
df = pd.DataFrame({'A': [1, 2, 3],
                   'B': [400, 500, 600]})
new_df = pd.DataFrame({'B': [4, 5, 6],
                       'C': [7, 8, 9]})

In [ ]:
df

In [ ]:
new_df

In [ ]:
df.update(new_df)
df